PACKAGE:
  NAME: satellighte
  ARCH: archs
  MODEL: models

MODEL:
  mobilenetv2:
    default:
      eurosat:
        v0:
          url: "https://github.com/canturan10/satellighte/releases/download/v0.0.2/mobilenetv2_default_eurosat.pth"
          onnx: "https://github.com/canturan10/satellighte/releases/download/v0.0.2/mobilenetv2_default_eurosat.onnx"
          quantize-onnx: "https://github.com/canturan10/satellighte/releases/download/v0.0.2/mobilenetv2_default_eurosat_quantize.onnx"
        v1:
          url: "https://github.com/canturan10/satellighte/releases/download/v0.0.11/mobilenetv2_default_eurosat.pth"
          onnx: "https://github.com/canturan10/satellighte/releases/download/v0.0.11/mobilenetv2_default_eurosat.onnx"
          quantize-onnx: "https://github.com/canturan10/satellighte/releases/download/v0.0.11/mobilenetv2_default_eurosat_quantize.onnx"
  efficientnet:
    b0:
      eurosat:
        v0:
          url: "https://github.com/canturan10/satellighte/releases/download/v0.1.0/efficientnet_b0_eurosat.pth"
          onnx: "https://github.com/canturan10/satellighte/releases/download/v0.1.0/efficientnet_b0_eurosat.onnx"
          quantize-onnx: "https://github.com/canturan10/satellighte/releases/download/v0.1.0/efficientnet_b0_eurosat.onnx"
